### PR TITLE
Add chinese link

### PR DESCRIPTION
**Pull request by chinanf-boy**
Is link to My repo ??
or translate folder

### CODE REVIEW

**Comment by ronami** [comment]
Thank you! 🏆

Can you add https://github.com/chinanf-boy/minipack-explain/blob/master/minipack.js and https://github.com/chinanf-boy/minipack-explain/blob/master/minipack.zh.md to the PR instead of the link? I think we can put them in a `translations/zh-cn` folder and link to it from the main README.md.

Each translation directory can look look like this with the translated files:

```
translations/
├── zh-cn/
│   ├── README.md
│   ├── src/
│   │   └── minipack.js
```

What do you think?

**Comment by ronami** [comment]
Hey @chinanf-boy, thank you! 🏆 

Adding a link to your repo would be great, just a few small requests:
- The link from https://github.com/chinanf-boy/minipack-explain/blob/master/minipack.zh.md to the (translated) `minipack.js` is broken because it's not inside `src` directory. 
- Can we please keep the same file structure as this repo? With the `example` and `src` directories. Maybe fork this repository? I really like the way translations are being added here: https://github.com/verekia/js-stack-from-scratch/blob/master/how-to-translate.md.
- Would it be okay with having https://github.com/chinanf-boy/minipack-explain/blob/master/minipack.zh.md the main readme (README.md) and link to the extra explanation (https://github.com/chinanf-boy/minipack-explain/blob/master/readme.md) from it?

Thanks a lot for your contribution and effort :)

**Comment by chinanf-boy** [comment]
### new UI
---
### Translations
 
- [中文](https://github.com/chinanf-boy/minipack-explain) by [chinanf-boy](https://github.com/chinanf-boy)
---
### My repo

https://github.com/chinanf-boy/minipack-explain

**Comment by ronami** [comment]
Looks great, thank you :)

Can you please also add the other missing files ([LICENSE](https://github.com/ronami/minipack/blob/master/LICENSE), [.eslintrc](https://github.com/ronami/minipack/blob/master/.eslintrc)) and a note somewhere explaining on the main `README.md` that this is a translation, with a link back to this repository.

Please fork this repository so all files and commits are retained and then add the translations on top of it.

**Comment by ronami** [comment]
Looks great :)

I think it’s important to also have the other missing files ([LICENSE](https://github.com/ronami/minipack/blob/master/LICENSE), [.eslintrc](https://github.com/ronami/minipack/blob/master/.eslintrc)) and a note somewhere explaining on the main `README.md` that this is a translation, with a link back to this repository.

If it’s not too much work, please fork this repository so all files and commits are retained and then add the translations on top of it.

Thank you 🙏

**Comment by chinanf-boy** [comment]
@ronami 

> https://github.com/chinanf-boy/minipack-explain

---
 
 这是一篇 `翻译{Translations}`

 [github source](https://github.com/ronami/minipack)

---

**Review by ronami — APPROVED** [review]
Great! Thank you for the translation!

**Pull request merged**
